### ISSUE TITLE
Add a speed control

### ISSUE THREAD

**Issue by lgpf** [MobyGamer/softhddi#4]
What about a speed control option.
I saw the clicker project, and also I made one with atiny85 very similar for fun.
But in mine, even in faster systems, once I get high on led activity I will enable sound for like 40ms and then apply a force cool down of 10ms. Even if there is thousands of clicks on a faster POS machine, it will ignore and act as a slow HD.
Would that be possible to add as an option (like O for Old and Slow HDD)?

**Comment by MobyGamer** [comment]
Adding something like this is tricky, because it clicks whenever a "seek" is made.  So it's accurate, but if you have it connected to a very fast drive, of course it will click faster.  Implementing this would be for trying to simulate a slower drive, but that's not really the intent of the project.  Also, it would require softhddi to hook the timer interrupt, and that would impact the system even more.

I appreciate the suggestion :) but it's not really in scope for this TSR.
